### ISSUE TITLE
Criar a parte visual do recebimento do e-mail de confirmação.

### ISSUE THREAD

**Issue by jefersonPradoMartins** [jefersonPradoMartins/Univida-Project#4]
Quando o usuário se cadastrar no app da univido será enviado um link que o usuário ao clicar vai confirmar a conta de e-mail como verdadeira. 

segue a baixo uma foto de como esta o envio.

![Image](https://github.com/jefersonPradoMartins/univida-app/assets/122683835/0ac96349-7971-4f28-b90f-650ed2e13178)

Seria interessante desenvolver uma identidade para esse e-mail.

**Comment by ellergus** [comment]
Protótipo navegavel criado:

https://www.figma.com/proto/J5hIR4nqoaFSD2jEY1Lgvi/Univida?page-id=0%3A1&type=design&node-id=144-12&viewport=840%2C-728%2C0.13&t=TlXZcJkva3rhlN9p-1&scaling=scale-down&starting-point-node-id=144%3A12&show-proto-sidebar=1&mode=design

**Comment by jefersonPradoMartins** [comment]
Funcionalidade de login finalizada.
